In [4]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install streamlit

  Using cached streamlit-1.54.0-py3-none-any.whl.metadata (9.8 kB)
  Using cached altair-6.0.0-py3-none-any.whl.metadata (11 kB)
  Using cached gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
  Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Using cached streamlit-1.54.0-py3-none-any.whl (9.1 MB)
Using cached altair-6.0.0-py3-none-any.whl (795 kB)
Using cached gitpython-3.1.46-py3-none-any.whl (208 kB)
Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.1
    Uninstalling pandas-3.0.1:
      Successfully uninstalled pandas-3.0.1
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
#load the datset
import pandas as pd
import numpy as np
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

In [5]:
test_df.head()

beds  baths    size size_units  lot_size lot_size_units  zip_code  \
0     3    3.0  2850.0       sqft   4200.00           sqft     98119   
1     4    5.0  3040.0       sqft   5002.00           sqft     98106   
2     3    1.0  1290.0       sqft   6048.00           sqft     98125   
3     3    2.0  2360.0       sqft      0.28           acre     98188   
4     3    3.5  1942.0       sqft   1603.00           sqft     98107   

       price  
0  1175000.0  
1  1057500.0  
2   799000.0  
3   565000.0  
4  1187000.0

In [6]:
#concatenate the train and test dataframes
full_df = pd.concat([train_df, test_df], ignore_index=True)

In [7]:
full_df.head()


beds  baths    size size_units  lot_size lot_size_units  zip_code  \
0     3    2.5  2590.0       sqft   6000.00           sqft     98144   
1     4    2.0  2240.0       sqft      0.31           acre     98106   
2     4    3.0  2040.0       sqft   3783.00           sqft     98107   
3     4    3.0  3800.0       sqft   5175.00           sqft     98199   
4     2    2.0  1042.0       sqft       NaN            NaN     98102   

       price  
0   795000.0  
1   915000.0  
2   950000.0  
3  1950000.0  
4   950000.0

In [8]:
#drop unecessary columns
full_df.drop(columns=["size_units", "lot_size_units", "lot_size","zip_code"], inplace=True)
full_df.head()

beds  baths    size      price
0     3    2.5  2590.0   795000.0
1     4    2.0  2240.0   915000.0
2     4    3.0  2040.0   950000.0
3     4    3.0  3800.0  1950000.0
4     2    2.0  1042.0   950000.0

In [9]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2521 entries, 0 to 2520
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   beds    2521 non-null   int64  
 1   baths   2521 non-null   float64
 2   size    2521 non-null   float64
 3   price   2521 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 78.9 KB


In [10]:
#change the data type of bath column
full_df['baths'] = full_df['baths'].astype(int)
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2521 entries, 0 to 2520
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   beds    2521 non-null   int64  
 1   baths   2521 non-null   int64  
 2   size    2521 non-null   float64
 3   price   2521 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 78.9 KB


In [11]:
full_df.isna().sum()

beds     0
baths    0
size     0
price    0
dtype: int64

In [12]:
#identify the input and output
X = full_df.drop('price',axis=1)
y = full_df['price']

In [13]:
X

beds  baths    size
0        3      2  2590.0
1        4      2  2240.0
2        4      3  2040.0
3        4      3  3800.0
4        2      2  1042.0
...    ...    ...     ...
2516     5      4  5580.0
2517     3      2  1390.0
2518     3      2  2950.0
2519     5      5  3010.0
2520     3      2  1301.0

[2521 rows x 3 columns]

In [14]:
y

0        795000.0
1        915000.0
2        950000.0
3       1950000.0
4        950000.0
          ...    
2516    3800000.0
2517     575000.0
2518    3105000.0
2519    1807000.0
2520     895000.0
Name: price, Length: 2521, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [16]:
from sklearn.linear_model import LinearRegression
house_price_mlr_model = LinearRegression()
house_price_mlr_model.fit(X_train, y_train)

LinearRegression()

In [17]:
house_price_mlr_model.coef_

array([-107504.66707237,   66072.12897555,     531.63017517])

In [18]:
house_price_mlr_model.intercept_

np.float64(200324.16446636594)

In [19]:
#Test the model
y_pred = house_price_mlr_model.predict(X_test)
y_pred[:5]

array([ 826388.38301166, 1279903.53800072,  715843.92214238,
        699594.13008695,  848751.46593558])

In [20]:
y_test[:5]

196     749900.0
986     800000.0
1090    675000.0
387     599950.0
2222    965000.0
Name: price, dtype: float64

In [21]:
#evaluate the model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)   
rmse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)   
print(mae,rmse,r2)

260637.76467654156 923486093784.5175 0.14450297750355146


In [22]:
#training the model on scaled or normalized data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [24]:
X_train_scaled[:5]

array([[-0.70187518,  3.14110327, -0.46324902],
       [ 0.09793607,  1.03829258, -0.48447141],
       [-0.70187518, -0.01311277, -0.89194128],
       [-1.50168644, -1.06451811, -1.14236547],
       [ 4.89680361,  3.14110327,  1.94549214]])

In [25]:
from sklearn.linear_model import LinearRegression
house_price_mlr_model_new = LinearRegression()
house_price_mlr_model_new.fit(X_train_scaled, y_train)

LinearRegression()

In [26]:
house_price_mlr_model_new.intercept_

np.float64(957785.9506802721)

In [27]:
house_price_mlr_model_new.coef_

array([-134412.54569187,   62841.72818487,  501008.79045428])

In [28]:
#predictions
y_pred_new = house_price_mlr_model_new.predict(X_test_scaled)
y_pred_new[:5]

array([ 826388.38301166, 1279903.5380007 ,  715843.92214238,
        699594.13008697,  848751.46593557])

In [29]:
#evaluate the model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error
mae = mean_absolute_error(y_test, y_pred_new)   
rmse = root_mean_squared_error(y_test, y_pred_new)
r2 = r2_score(y_test, y_pred_new)
print(mae,rmse,r2)

260637.76467654435 960981.8384259488 0.14450297750355245


In [30]:
#save the model
import joblib as jb
jb.dump(house_price_mlr_model_new, "House_Price_Predictor.pkl")

['House_Price_Predictor.pkl']

In [31]:
X.columns

Index(['beds', 'baths', 'size'], dtype='object')

In [ ]:
#load the model
loaded_model = jb.load("House_Price_Predictor.pkl")
bed = int(input("Enter the number of bedrooms: "))
bath = int(input("Enter the number of bathrooms: "))
sz = float(input("Enter the size of the house in sqmt: "))
input_data = np.array([[bed, bath, sz]])
input_data_scaled = scaler.transform(input_data)
prediction = loaded_model.predict(input_data_scaled)
print("The predicted price of the house is: ", f"{prediction[0]:.2f}")

TypeError: array() got an unexpected keyword argument 'columns'