In [1]:
import numpy as np

In [2]:
list(dir(np))

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [ ]:
# Numbers = int, float, complex
# Boolean = True and False
# set = set()
# dict = dict()
# sequence = list,tuple and string

In [4]:
#intro to ML

In [5]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   -------------------------------


[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import seaborn as sns
data = sns.load_dataset('titanic')
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    str     
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    str     
 8   class        891 non-null    category
 9   who          891 non-null    str     
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str     
 13  alive        891 non-null    str     
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB


In [9]:
data.sample(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
224         1       1    male  38.0      1      0  90.0000        S   First   
565         0       3    male  24.0      2      0  24.1500        S   Third   
514         0       3    male  24.0      0      0   7.4958        S   Third   
416         1       2  female  34.0      1      1  32.5000        S  Second   
361         0       2    male  29.0      1      0  27.7208        C  Second   
233         1       3  female   5.0      4      2  31.3875        S   Third   
630         1       1    male  80.0      0      0  30.0000        S   First   
362         0       3  female  45.0      0      1  14.4542        C   Third   
107         1       3    male   NaN      0      0   7.7750        S   Third   
155         0       1    male  51.0      0      1  61.3792        C   First   

       who  adult_male deck  embark_town alive  alone  
224    man        True    C  Southampton   yes  False  
565    man        True  NaN  Southampton    no  False  
514    man        True  NaN  Southampton    no   True  
416  woman       False  NaN  Southampton   yes  False  
361    man        True  NaN    Cherbourg    no  False  
233  child       False  NaN  Southampton   yes  False  
630    man        True    A  Southampton   yes   True  
362  woman       False  NaN    Cherbourg    no  False  
107    man        True  NaN  Southampton   yes   True  
155    man        True  NaN    Cherbourg    no  False

In [10]:
#Deleting the single column
data.drop("embarked",axis = 1, inplace = True)

In [11]:
data.head()


survived  pclass     sex   age  sibsp  parch     fare  class    who  \
0         0       3    male  22.0      1      0   7.2500  Third    man   
1         1       1  female  38.0      1      0  71.2833  First  woman   
2         1       3  female  26.0      0      0   7.9250  Third  woman   
3         1       1  female  35.0      1      0  53.1000  First  woman   
4         0       3    male  35.0      0      0   8.0500  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [12]:
#deleting the single column
data.drop("class", axis = 1, inplace = True)
data.head()

survived  pclass     sex   age  sibsp  parch     fare    who  adult_male  \
0         0       3    male  22.0      1      0   7.2500    man        True   
1         1       1  female  38.0      1      0  71.2833  woman       False   
2         1       3  female  26.0      0      0   7.9250  woman       False   
3         1       1  female  35.0      1      0  53.1000  woman       False   
4         0       3    male  35.0      0      0   8.0500    man        True   

  deck  embark_town alive  alone  
0  NaN  Southampton    no  False  
1    C    Cherbourg   yes  False  
2  NaN  Southampton   yes   True  
3    C  Southampton   yes  False  
4  NaN  Southampton    no   True

In [13]:
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [16]:
data['age'].fillna(data['age'].mean(), inplace = True)
data.isna().sum()

C:\Users\Avantee Sarve\AppData\Local\Temp\ipykernel_24900\3696548041.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['age'].fillna(data['age'].mean(), inplace = True)


survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [17]:
data['age'] = data['sex'].astype(str)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    str     
 3   age          891 non-null    str     
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   who          891 non-null    str     
 8   adult_male   891 non-null    bool    
 9   deck         203 non-null    category
 10  embark_town  889 non-null    str     
 11  alive        891 non-null    str     
 12  alone        891 non-null    bool    
dtypes: bool(2), category(1), float64(1), int64(4), str(5)
memory usage: 72.7 KB


In [18]:
data['sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [19]:
data['pclass'].unique()

array([3, 1, 2])

In [20]:
data["parch"].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [21]:
data['sibsp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [22]:
data['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [23]:
data['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [25]:
#One hot encoding to encode the 'sex' column
import pandas as pd
data_encoded = pd.get_dummies(columns = ['sex'], data = data, dtype = int, drop_first = True)
data_encoded.head()

survived  pclass     age  sibsp  parch     fare    who  adult_male deck  \
0         0       3    male      1      0   7.2500    man        True  NaN   
1         1       1  female      1      0  71.2833  woman       False    C   
2         1       3  female      0      0   7.9250  woman       False  NaN   
3         1       1  female      1      0  53.1000  woman       False    C   
4         0       3    male      0      0   8.0500    man        True  NaN   

   embark_town alive  alone  sex_male  
0  Southampton    no  False         1  
1    Cherbourg   yes  False         0  
2  Southampton   yes   True         0  
3  Southampton   yes  False         0  
4  Southampton    no   True         1

In [26]:
#save the file
data_encoded.to_csv('titanic_encoded.csv', index = False)